---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    security_autoupdate_reboot: "false"
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Install openssh-server for configuration
      ansible.builtin.apt:
        name: openssh-server
        state: present
    - name: Include security role
      ansible.builtin.include_role:
        name: jezmn.ansible_hardened_docker_host.security
